module Redmine::SyntaxHighlighting::Pygments
  class << self
    def highlight_by_filename(text, filename)
      language = case File.basename(filename)
when /\.feature$/ then 'Cucumber'
when /\.abap$/ then 'abap'
when /\.adb$|\.ads$|\.ada$/ then 'ada'
when /\.ahk$|\.ahkl$/ then 'ahk'
when /\.G$|\.g$/ then 'antlr-as'
when /\.G$|\.g$/ then 'antlr-cpp'
when /\.G$|\.g$/ then 'antlr-csharp'
when /\.G$|\.g$/ then 'antlr-java'
when /\.G$|\.g$/ then 'antlr-objc'
when /\.G$|\.g$/ then 'antlr-perl'
when /\.G$|\.g$/ then 'antlr-python'
when /\.G$|\.g$/ then 'antlr-ruby'
when /^\.htaccess$|^apache\.conf$|^apache2\.conf$/ then 'apacheconf'
when /\.applescript$/ then 'applescript'
when /\.as$/ then 'as'
when /\.as$/ then 'as3'
when /\.aspx$|\.asax$|\.ascx$|\.ashx$|\.asmx$|\.axd$/ then 'aspx-cs'
when /\.aspx$|\.asax$|\.ascx$|\.ashx$|\.asmx$|\.axd$/ then 'aspx-vb'
when /\.asy$/ then 'asy'
when /\.awk$/ then 'awk'
when /\.sh$|\.ksh$|\.bash$|\.ebuild$|\.eclass$|^\.bashrc$|^bashrc$|^\.bash_|^bash_/ then 'bash'
when /\.bat$|\.cmd$/ then 'bat'
when /\.befunge$/ then 'befunge'
when /\.bmx$/ then 'blitzmax'
when /\.boo$/ then 'boo'
when /\.bf$|\.b$/ then 'brainfuck'
when /\.bro$/ then 'bro'
when /\.c-objdump$/ then 'c-objdump'
when /\.c$|\.h$|\.idc$/ then 'c'
when /\.cf$/ then 'cfengine3'
when /\.cfm$|\.cfml$|\.cfc$/ then 'cfm'
when /\.tmpl$|\.spt$/ then 'cheetah'
when /\.clj$/ then 'clojure'
when /\.cmake$|^CMakeLists\.txt$/ then 'cmake'
when /\.coffee$/ then 'coffee-script'
when /\.cl$|\.lisp$|\.el$/ then 'common-lisp'
when /\.sh-session$/ then 'console'
when /^control$/ then 'control'
when /\.v$/ then 'coq'
when /\.cpp$|\.hpp$|\.c++$|\.h++$|\.cc$|\.hh$|\.cxx$|\.hxx$/ then 'cpp'
when /\.cpp-objdump$|\.c++-objdump$|\.cxx-objdump$/ then 'cpp-objdump'
when /\.cs$/ then 'csharp'
when /\.css$/ then 'css'
when /\.pyx$|\.pxd$|\.pxi$/ then 'cython'
when /\.d-objdump$/ then 'd-objdump'
when /\.d$|\.di$/ then 'd'
when /\.dart$/ then 'dart'
when /\.pas$/ then 'delphi'
when /\.diff$|\.patch$/ then 'diff'
when /\.dpatch$|\.darcspatch$/ then 'dpatch'
when /\.dtd$/ then 'dtd'
when /\.duel$|\.jbst$/ then 'duel'
when /\.dylan$|\.dyl$/ then 'dylan'
when /\.ec$|\.eh$/ then 'ec'
when /\.ecl$/ then 'ecl'
when /\.ex$|\.exs$/ then 'elixir'
when /\.erl-sh$/ then 'erl'
when /\.erl$|\.hrl$|\.es$|\.escript$/ then 'erlang'
when /\.evoque$/ then 'evoque'
when /\.factor$/ then 'factor'
when /\.fan$/ then 'fan'
when /\.fy$|\.fancypack$/ then 'fancy'
when /\.flx$|\.flxh$/ then 'felix'
when /\.f$|\.f90$|\.F$|\.F90$/ then 'fortran'
when /\.fs$|\.fsi$/ then 'fsharp'
when /\.s$|\.S$/ then 'gas'
when /\.kid$/ then 'genshi'
when /\.vert$|\.frag$|\.geo$/ then 'glsl'
when /\.plot$|\.plt$/ then 'gnuplot'
when /\.go$/ then 'go'
when /\.gdc$/ then 'gooddata-cl'
when /\.gs$|\.gsx$|\.gsp$|\.vark$/ then 'gosu'
when /\.[1234567]$|\.man$/ then 'groff'
when /\.groovy$/ then 'groovy'
when /\.gst$/ then 'gst'
when /\.haml$/ then 'haml'
when /\.hs$/ then 'haskell'
when /\.html$/ then 'html+evoque'
when /\.phtml$/ then 'html+php'
when /\.html$|\.htm$|\.xhtml$|\.xslt$/ then 'html'
when /\.hx$/ then 'hx'
when /\.hy$|\.hyb$/ then 'hybris'
when /\.ini$|\.cfg$/ then 'ini'
when /\.io$/ then 'io'
when /\.ik$/ then 'ioke'
when /\.weechatlog$/ then 'irc'
when /\.jade$/ then 'jade'
when /\.java$/ then 'java'
when /\.js$/ then 'js'
when /\.json$/ then 'json'
when /\.jsp$/ then 'jsp'
when /\.kt$/ then 'kotlin'
when /\.lhs$/ then 'lhs'
when /\.ll$/ then 'llvm'
when /\.lgt$/ then 'logtalk'
when /\.lua$|\.wlua$/ then 'lua'
when /\.mak$|^Makefile$|^makefile$|^Makefile\.|^GNUmakefile$/ then 'make'
when /\.mao$/ then 'mako'
when /\.maql$/ then 'maql'
when /\.m$|\.mhtml$|\.mc$|\.mi$|^autohandler$|^dhandler$/ then 'mason'
when /\.m$/ then 'matlab'
when /\.md$/ then 'minid'
when /\.mo$/ then 'modelica'
when /\.def$|\.mod$/ then 'modula2'
when /\.moo$/ then 'moocode'
when /\.moon$/ then 'moon'
when /\.mu$/ then 'mupad'
when /\.mxml$/ then 'mxml'
when /\.myt$|^autodelegate$/ then 'myghty'
when /\.asm$|\.ASM$/ then 'nasm'
when /\.n$/ then 'nemerle'
when /\.lsp$|\.nl$/ then 'newlisp'
when /\.ns2$/ then 'newspeak'
when /\.nim$|\.nimrod$/ then 'nimrod'
when /\.objdump$/ then 'objdump'
when /\.m$/ then 'objective-c'
when /\.j$/ then 'objective-j'
when /\.ml$|\.mli$|\.mll$|\.mly$/ then 'ocaml'
when /\.m$/ then 'octave'
when /\.ooc$/ then 'ooc'
when /\.opa$/ then 'opa'
when /\.p$|\.cls$/ then 'openedge'
when /\.pl$|\.pm$/ then 'perl'
when /\.php$|\.php[345]$/ then 'php'
when /\.ps$|\.eps$/ then 'postscript'
when /\.pot$|\.po$/ then 'pot'
when /\.pov$|\.inc$/ then 'pov'
when /\.ps1$/ then 'powershell'
when /\.prolog$|\.pro$|\.pl$/ then 'prolog'
when /\.properties$/ then 'properties'
when /\.proto$/ then 'protobuf'
when /\.py3tb$/ then 'py3tb'
when /\.pypylog$/ then 'pypylog'
when /\.pytb$/ then 'pytb'
when /\.py$|\.pyw$|\.sc$|^SConstruct$|^SConscript$|\.tac$/ then 'python'
when /\.rl$/ then 'ragel-c'
when /\.rl$/ then 'ragel-cpp'
when /\.rl$/ then 'ragel-d'
when /\.rl$/ then 'ragel-em'
when /\.rl$/ then 'ragel-java'
when /\.rl$/ then 'ragel-objc'
when /\.rl$/ then 'ragel-ruby'
when /\.rb$|\.rbw$|^Rakefile$|\.rake$|\.gemspec$|\.rbx$|\.duby$/ then 'rb'
when /\.Rout$/ then 'rconsole'
when /\.r$|\.r3$/ then 'rebol'
when /\.cw$/ then 'redcode'
when /\.rhtml$/ then 'rhtml'
when /\.rst$|\.rest$/ then 'rst'
when /\.sass$/ then 'sass'
when /\.scala$/ then 'scala'
when /\.scaml$/ then 'scaml'
when /\.scm$|\.ss$|\.rkt$/ then 'scheme'
when /\.sci$|\.sce$|\.tst$/ then 'scilab'
when /\.scss$/ then 'scss'
when /\.st$/ then 'smalltalk'
when /\.tpl$/ then 'smarty'
when /\.sml$|\.sig$|\.fun$/ then 'sml'
when /\.snobol$/ then 'snobol'
when /^sources\.list$/ then 'sourceslist'
when /\.S$|\.R$/ then 'splus'
when /\.sql$/ then 'sql'
when /\.sqlite3-console$/ then 'sqlite3'
when /^squid\.conf$/ then 'squidconf'
when /\.ssp$/ then 'ssp'
when /\.sv$|\.svh$/ then 'sv'
when /\.tcl$/ then 'tcl'
when /\.tcsh$|\.csh$/ then 'tcsh'
when /\.tea$/ then 'tea'
when /\.tex$|\.aux$|\.toc$/ then 'tex'
when /\.txt$/ then 'text'
when /\.u$/ then 'urbiscript'
when /\.v$/ then 'v'
when /\.vala$|\.vapi$/ then 'vala'
when /\.vb$|\.bas$/ then 'vb.net'
when /\.vm$|\.fhtml$/ then 'velocity'
when /\.vhdl$|\.vhd$/ then 'vhdl'
when /\.vim$|^\.vimrc$|^\.exrc$|^\.gvimrc$|^_vimrc$|^_exrc$|^_gvimrc$|^vimrc$|^gvimrc$/ then 'vim'
when /\.xml$/ then 'xml+evoque'
when /\.xml$|\.xsl$|\.rss$|\.xslt$|\.xsd$|\.wsdl$/ then 'xml'
when /\.xqy$|\.xquery$/ then 'xquery'
when /\.xsl$|\.xslt$/ then 'xslt'
when /\.yaml$|\.yml$/ then 'yaml'
      end

      if language then
        hl_option = "-l #{language}"
      else
        hl_option = '-g'
      end
      #"#{filename.inspect}:)" + text
      code = IO.popen("pygmentize #{hl_option} -f html", 'w+') do |pipe|
        pipe.print(text)
        pipe.close_write
        pipe.read
      end
      code = code.sub(/^<div class="highlight"><pre>/, '').sub(/\n<\/pre><\/div>$/, '')
    end

    def highlight_by_language(text, language)
      unless language =~ /^[a-z]+$/
      "#{language.inspect}:)" + text
else
      code = IO.popen("pygmentize -l #{language} -f html", 'w+') do |pipe|
        pipe.puts(text)
        pipe.close_write
        pipe.read
      end
      code = code.sub(/^<div class="highlight"><pre>/, '').sub(/\n<\/pre><\/div>$/, '')
end
    end
  end
end

Redmine::SyntaxHighlighting.highlighter = 'Pygments'
